name: 'JavaScript Action Example'
description: 'JavaScript Action Example'
author: 'Shane'
branding:
    icon: 'code'
    color: 'green'

inputs:
    file:
        description: 'JSON File'
        required: true
    version:
        description: 'Version'
        required: false

runs:
    using: 'node20'
    main: 'dist/index.js'
