name: "JavaScript Action Example"
description: "JavaScript Action Example"
author: "Shane"
branding:
  icon: "code"
  color: "green"

inputs:
  file:
    description: "JSON File"
    required: true
  version:
    description: "Set Version"
    required: false
  key:
    description: "Version Key"
    required: false
    default: "version"

runs:
  using: "node20"
  main: "src/index.js"
